import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "./all.min.css";

const poppins = localFont({
  src: [
    { path: "./fonts/Poppins.ttf", weight: "400" },
    { path: "./fonts/Poppins-SemiBold.ttf", weight: "600" },
    { path: "./fonts/Poppins-Bold.ttf", weight: "700" },
    { path: "./fonts/Poppins-ExtraBold.ttf", weight: "800" },
  ],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Tokokay - Online Store for Gen Z",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${poppins.variable} antialiased`}>{children}</body>
    </html>
  );
}
